export type CaptureDetail = {
  id: number;
  stem: string;
  parent_relative: string;
  captured_at: string | null;
  pairing_status: string;
  event_name: string | null;
  category: string | null;
  technical_score: number | null;
  exposure_score: number | null;
  sharpness_score: number | null;
  exif_score: number | null;
  shadow_clip_pct: number | null;
  highlight_clip_pct: number | null;
  histogram: number[] | null;
  auto_rating: number | null;
  user_rating: number | null;
  user_pick: number | null;
  user_reject: number | null;
  user_note: string | null;
  selection_reasons: string[];
  issues: Array<{ code: string; severity: string; message: string; evidence?: Record<string, unknown> }>;
  shooting_review: {
    summary: string | null;
    subject_type: string | null;
    overall_confidence: number | null;
    observations: Array<{
      phenomenon: string;
      evidence: string | null;
      severity: string | null;
      confidence: number | null;
      repairability: "limited" | "partial" | "unknown";
      repairability_label: string;
      source: "model";
    }>;
    next_time: Array<{
      suggestion: string;
      reason: string | null;
      exif_basis: string | null;
      source: "model";
    }>;
    editing: Array<{
      adjustment: string;
      direction: string | null;
      reason: string | null;
      tool: "Lightroom";
    }>;
    photoshop: { needed: boolean; reason: string | null } | null;
    technical_evidence: Array<{
      code: string;
      message: string;
      severity: string | null;
      evidence: Record<string, unknown>;
      inference: boolean;
      source: "technical";
    }>;
    has_model_result: boolean;
  };
  tags: CaptureTag[];
  tag_catalog: CaptureTagDefinition[];
  files: Array<{
    file_name: string;
    role: string;
    size_bytes: number;
    camera_model: string | null;
    lens_model: string | null;
    exposure_time: number | null;
    f_number: number | null;
    iso: number | null;
    focal_length_mm: number | null;
    focal_length_35mm: number | null;
    exposure_compensation: number | null;
    width: number | null;
    height: number | null;
    gps_latitude: number | null;
    gps_longitude: number | null;
    metering_mode: string | null;
    white_balance: string | null;
    flash: string | null;
    focus_mode: string | null;
    film_simulation: string | null;
    dynamic_range: string | null;
    exposure_program: string | number | null;
    exposure_mode: string | number | null;
    shutter_type: string | number | null;
    orientation: string | number | null;
    captured_at_precise: string | null;
    timezone_offset: string | null;
    color_space: string | number | null;
    bits_per_sample: string | number | number[] | null;
    image_quality: string | number | null;
    image_stabilization: string | number | number[] | null;
    drive_mode: string | number | null;
    drive_speed: string | number | null;
    sequence_number: string | number | null;
    auto_bracketing: string | number | null;
    af_mode: string | number | null;
    af_area_mode: string | number | null;
    focus_pixel: string | number | number[] | null;
    blur_warning: string | number | null;
    focus_warning: string | number | null;
    exposure_warning: string | number | null;
    faces_detected: string | number | null;
    roll_angle: string | number | null;
    camera_elevation_angle: string | number | null;
    white_balance_fine_tune: string | number | number[] | null;
    highlight_tone: string | number | null;
    shadow_tone: string | number | null;
    saturation: string | number | null;
    camera_sharpness: string | number | null;
    noise_reduction: string | number | null;
    clarity: string | number | null;
    color_chrome_effect: string | number | null;
    color_chrome_fx_blue: string | number | null;
    grain_effect_roughness: string | number | null;
    grain_effect_size: string | number | null;
    lens_modulation_optimizer: string | number | null;
    auto_dynamic_range: string | number | null;
    raw_compression: string | number | null;
  }>;
  ai_analyses: Array<{
    id: number;
    model_id: string;
    prompt_version: string;
    finished_at: string;
    result: Record<string, unknown>;
    user_verdict: "accurate" | "partial" | "inaccurate" | null;
    user_note: string | null;
    reviewed_at: string | null;
  }>;
  edit_recipes: EditRecipe[];
  thumbnail_url: string;
};

export type EditParameters = {
  exposure_ev: number;
  contrast: number;
  highlights: number;
  shadows: number;
  temperature: number;
  tint: number;
  saturation: number;
  sharpness: number;
};

export type EditRecipe = {
  id: number;
  capture_id: number;
  source_analysis_id: number | null;
  parameter_space: "tangerine-preview-v1";
  parameters: EditParameters;
  status: "draft" | "accepted" | "dismissed";
  note: string | null;
  created_at: string;
};

export type CaptureTagDimension = "subject" | "status" | "problem" | "location";
export type CaptureTagDefinition = {
  id: number;
  dimension: CaptureTagDimension;
  name: string;
  built_in: number;
};
export type CaptureTag = CaptureTagDefinition & {
  source: "manual" | "analysis" | "import";
  confidence: number | null;
};
